name: 'Dev.to Publish'
description: 'publish local markdown directory to dev.to'
inputs:
  directory:
    description: 'directory containing markdown posts'
    required: true
  api-key:
    description: 'dev.to api key, used to publish posts.'
    required: true
  state-file:
    description: 'json state file mapping files to known post Ids'
    required: false
    default: "ids.json"
outputs:
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "--apikey"
    - "${{ inputs.api-key }}"
    - "--state"
    - ${{ inputs.state-file }}
    - "--post_dir"
    - ${{ inputs.directory }}